# individual risc evaluation parameters
##### let $d_{i,j}$ be the distance between person $i$ and person $j$
##### the individual risk of person $i$ w.r.t. person $j$ is given by the followng formula:
######### $\eta \cdot e^{-\beta \cdot \max(0, d_{i, j} - \tau)}$
ETA: 1
BETA: 3
TAU: 1

# global risk evaluation parameters:
##### what is the maximum number of people that the monitored area should host?
AREA_CAPACITY: 5

# default matrix point in the real world used to find the homography transformation matrix
# [ [ (-1, -1), (0, -1), (1, -1) ]
# [ (-1, 0), (0, 0), (1, 0) ]
# [ (-1, 1), (0, 1), (1, 1) ] ]
DEFAULT_REAL_WORLD_POINTS:
  - - -1
    - -1
  - - 0
    - -1
  - - 1
    - -1
  - - -1
    - 0
  - - 0
    - 0
  - - 1
    - 0
  - - -1
    - 1
  - - 0
    - 1
  - - 1
    - 1

# DEFAULT_REAL_WORLD_POINTS multiplier
GRID_SCALE: 1.0

# worker unique id inside k4sme platform, make that all worker has different unique id
WORKER_ID: 1

# AI service to ask for --> all, [line_crossing, fall_detection, pandemic_monitoring]
SERVICE: all

VIDEO_PATH: resources/sample_03.mp4